# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_parse_CIGAR <- function(chrom, flag, pos, CIGAR, SEQ_len) {
    .Call('_paristools_test_parse_CIGAR', PACKAGE = 'paristools', chrom, flag, pos, CIGAR, SEQ_len)
}

sam_to_locs <- function(sam) {
    .Call('_paristools_sam_to_locs', PACKAGE = 'paristools', sam)
}

test2 <- function(df) {
    .Call('_paristools_test2', PACKAGE = 'paristools', df)
}

get_strand <- function(flag) {
    .Call('_paristools_get_strand', PACKAGE = 'paristools', flag)
}

test_as_locs <- function() {
    .Call('_paristools_test_as_locs', PACKAGE = 'paristools')
}

cpp_version <- function() {
    .Call('_paristools_cpp_version', PACKAGE = 'paristools')
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_paristools_RcppExport_registerCCallable', PACKAGE = 'paristools')
})
